### ISSUE TITLE
Free functions are ignored

### ISSUE THREAD

**Issue by TobBrandt** [derekwyatt/vim-protodef#1]
When I pull in the prototypes of the following file, the free funtion bar is ignored:

```
class Foo {
public:
  Foo(); // this works
};

void bar(); // this doesn't
```

,PP produces this:

```
Foo::Foo()
{
}
```

The ctags output seems correct:

```
Foo include/Foo.hpp /^  Foo();$/;"  line:3  class:Foo
bar include/Foo.hpp /^void bar();$/;"   line:6
```

stats:
- protodef 0.9.5
- ctags 5.8
- perl 5.10.1
- fswitch 0.9.3
- vim 7.2

**Comment by derekwyatt** [comment]
Yeah, it doesn't really support those... I'm not too keen on adding that, personally, but if you're willing to do it, I'll merge it in and push it out.

**Comment by TobBrandt** [comment]
> Yeah, it doesn't really support those...

Are you sure? In this demo video, it does: http://vimeo.com/4448265. Is that an old version?

**Comment by derekwyatt** [comment]
Really?  Heh :)  Crap.  I don't code C++ much anymore so I haven't used the plugin in quite a while... I'll try and take a look at it soon.
