### ISSUE TITLE
error on mac

### ISSUE THREAD

**Issue by zhangyl4991** [derekwyatt/vim-protodef#13]
Error detected while processing function protodef#ReturnSkeletonsFromPrototypesForCurrentBuffer[2]..<SNR>41_GetFun
ctionPrototypesForCurrentBuffer:
line   25:
E684: list index out of range: 3
Press ENTER or type command to continue
Error detected while processing function protodef#ReturnSkeletonsFromPrototypesForCurrentBuffer[2]..<SNR>41_GetFun
ctionPrototypesForCurrentBuffer:
line   25:
E116: Invalid arguments for function matchstr(parts[3], ':\zs.*\ze')
Press ENTER or type command to continue
Error detected while processing function protodef#ReturnSkeletonsFromPrototypesForCurrentBuffer[2]..<SNR>41_GetFun
ctionPrototypesForCurrentBuffer:
line   47:
E121: Undefined variable: linenum
Press ENTER or type command to continue
Error detected while processing function protodef#ReturnSkeletonsFromPrototypesForCurrentBuffer[2]..<SNR>41_GetFun
ctionPrototypesForCurrentBuffer:
line   47:
E116: Invalid arguments for function add
Press ENTER or type command to continue
Error detected while processing function protodef#ReturnSkeletonsFromPrototypesForCurrentBuffer[2]..<SNR>41_GetFun
ctionPrototypesForCurrentBuffer:
line   25:
E684: list index out of range: 3
Press ENTER or type command to continue
Error detected while processing function protodef#ReturnSkeletonsFromPrototypesForCurrentBuffer[2]..<SNR>41_GetFun
ctionPrototypesForCurrentBuffer:
line   25:
E116: Invalid arguments for function matchstr(parts[3], ':\zs.*\ze')
Press ENTER or type command to continue
Error detected while processing function protodef#ReturnSkeletonsFromPrototypesForCurrentBuffer[2]..<SNR>41_GetFun
ctionPrototypesForCurrentBuffer:
line   47:
E121: Undefined variable: linenum
Press ENTER or type command to continue
Error detected while processing function protodef#ReturnSkeletonsFromPrototypesForCurrentBuffer[2]..<SNR>41_GetFun
ctionPrototypesForCurrentBuffer:
line   47:
E116: Invalid arguments for function add

**Comment by derekwyatt** [comment]
I don't use protodef anymore (and haven't for a _very_ long time) but my guess is that your `ctags` is wrong. Check the docs and make sure you've got the right `ctags` running.

**Comment by zhangyl4991** [comment]
thanks, it works fine after I installed Exuberant Ctags.
