### ISSUE TITLE
Protodef doesn't play well with Qt

### ISSUE THREAD

**Issue by derekwyatt** [derekwyatt/vim-protodef#2]
Qt introduces new syntax into C++ header files - namely 'slots:' and 'signals:'.  Protodef doesn't recognize these and, while slots aren't a problem, signals are.  Signals don't have implementation, but since it doesn't understand that, it pulls them into the file.  Bad stuff.

**Comment by marvin2k** [comment]
looks good, thanks a lot!

**Comment by derekwyatt** [comment]
No, it looks like shit... but it works :)

No problem.  I've been doing some Qt work lately as well, and this has been a problem.  Thanks for pushing me to fix it.
